
- hosts: localhost
  connection: local
  become: no
  gather_facts: no
  roles:
    - macos
    - dotenv
    - alias
    - java
    - brew-cask
    - brew
    - asdf
    - git
    - mysql
    - k8s
    - zsh
  vars:
    brew_repositories:
      - homebrew/services
    brew_packages:
      - { name: openssl }
      - { name: libffi }
      - { name: coreutils }
      - { name: ghq }
      - { name: git }
      - { name: gnupg }
      - { name: graphviz }
      - { name: htop }
      - { name: jq }
      - { name: neovim }
      - { name: peco }
      - { name: tree }
      - { name: wget }
      - { name: zsh }
      - { name: asdf }
      - { name: composer }
      - { name: mysql@5.7 }
      - { name: redis }
      - { name: sqlite }
      - { name: kubectx }
      - { name: kubernetes-cli }
      - { name: kube-ps1 }
      - { name: kustomize }
      - { name: stern }
      - { name: awscli }
      - { name: aws-iam-authenticator }
      - { name: s3cmd }
      - { name: embulk }
    brew_cask_repositories:
      - homebrew/cask-versions
    brew_cask_packages:
      - { name: alfred }
      - { name: appcleaner }
      - { name: bettertouchtool }
      - { name: clipy }
      - { name: dropbox }
      - { name: google-chrome }
      - { name: iterm2 }
      - { name: slack }
      - { name: adoptopenjdk8 }
      - { name: docker }
      - { name: kitematic }
      - { name: vagrant }
      - { name: visual-studio-code }
    macos_global_defaults:
      - key: AppleInterfaceStyle
        type: string
        value: Dark
      - key: AppleLanguages
        type: array
        value:
          - 'ja-JP'
          - 'en-JP'
      - key: AppleLocale
        type: string
        value: 'ja-JP'
      - key: AppleMeasurementUnits
        type: string
        value: Centimeters
      - key: AppleMetricUnits
        type: bool
        value: true
      - key: AppleTemperatureUnit
        type: string
        value: Celsius
    macos_app_defaults:
      - domain: dock
        key: orientation
        type: string
        value: left
      - domain: dock
        key: autohide
        type: bool
        value: true
      - domain: finder
        key: AppleShowAllFiles
        type: string
        value: YES
      - domain: systemuiserver
        key: menuExtras
        type: array
        value:
          - '/System/Library/CoreServices/Menu Extras/Battery.menu'
          - '/System/Library/CoreServices/Menu Extras/Bluetooth.menu'
          - '/System/Library/CoreServices/Menu Extras/Clock.menu'
      - domain: menuextra.battery
        key: ShowPercent
        type: string
        value: YES
