---
- name: load alias file
  lineinfile:
    dest: ~/.bash_profile
    line: "source {{ myhome_conf_dir }}/alias.sh"
- name: copy alias file
  copy:
    src: ../files/alias.sh
    dest: "{{ myhome_conf_dir }}/alias.sh"
    mode: 0755
