---
- name: load kube-ps1 file
  lineinfile:
    dest: ~/.zshrc
    line: 'source /usr/local/opt/kube-ps1/share/kube-ps1.sh'
- name: set kube-ps1 environment variables
  lineinfile:
    dest: ~/.zshrc
    line: 'PROMPT="$(kube_ps1) "$PROMPT'
- name: hide kube-ps1
  lineinfile:
    dest: ~/.zshrc
    line: 'kubeoff'
