---
- name: load kube-ps1 file
  lineinfile:
    dest: ~/.zshrc
    line: "source /opt/homebrew/opt/kube-ps1/share/kube-ps1.sh"
- name: set kube-ps1 environment variables
  blockinfile:
    dest: ~/.zshrc
    content: |
      source /opt/homebrew/opt/kube-ps1/share/kube-ps1.sh
      PROMPT='$(kube_ps1) '$PROMPT
      kubeoff
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK for kube-ps1"
