---
# asdf
- name: set asdf environment variables
  lineinfile:
    dest: ~/.bash_profile
    line: 'export ASDF_PREFIX="/usr/local/opt/asdf"'
- name: load asdf file
  lineinfile:
    dest: ~/.bash_profile
    line: 'source $ASDF_PREFIX/asdf.sh'
- name: load asdf bash file
  lineinfile:
    dest: ~/.bash_profile
    line: 'source $ASDF_PREFIX/etc/bash_completion.d/asdf.bash'
- name: create asdf directory
  file:
    path: ~/.asdf
    state: directory
    mode: 0755

# golang
- name: check golang
  stat:
    path: ~/.asdf/plugins/golang
  register: golangresult
- name: install golang
  shell: asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
  when: not golangresult.stat.exists
- name: install latest golang
  shell: asdf install golang $(asdf list-all golang | grep -v beta | grep -v rc | tail -n 1)
- name: set latest golang version
  shell: asdf global golang $(asdf list-all golang | grep -v beta | grep -v rc | tail -n 1)

# nodejs
- name: check nodejs
  stat:
    path: ~/.asdf/plugins/nodejs
  register: nodejsresult
- name: install nodejs
  shell: asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  when: not nodejsresult.stat.exists
- name: install latest nodejs
  shell: asdf install nodejs $(asdf list-all nodejs | sort -r | head -n 1)
- name: set latest nodejs version
  shell: asdf global nodejs $(asdf list-all nodejs | sort -r | head -n 1)

# python
- name: check python
  stat:
    path: ~/.asdf/plugins/python
  register: pythonresult
- name: install python
  shell: asdf plugin-add python https://github.com/danhper/asdf-python.git
  when: not pythonresult.stat.exists
- name: install latest python3
  shell: asdf install python $(asdf list-all python | grep "^3.*" | grep -v dev | sort -r | head -n 1)
- name: set latest python
  shell: asdf global python $(asdf list-all python | grep "^3.*" | grep -v dev | sort -r | head -n 1)

# ruby
- name: set ruby environment variables
  lineinfile:
    dest: ~/.bash_profile
    line: 'export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"'
- name: check ruby
  stat:
    path: ~/.asdf/plugins/ruby
  register: rubyresult
- name: install ruby
  shell: asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
  when: not rubyresult.stat.exists
- name: install latest ruby
  shell: asdf install ruby $(asdf list-all ruby | grep "^\d.*" | grep -v dev | grep -v preview | grep -v rc | sort -r | head -n 1)
- name: set latest ruby version
  shell: asdf global ruby $(asdf list-all ruby | grep "^\d.*" | grep -v dev | grep -v preview | grep -v rc | sort -r | head -n 1)

# terraform
- name: check terraform
  stat:
    path: ~/.asdf/plugins/terraform
  register: tfresult
- name: install terrafrom
  shell: asdf plugin-add terraform https://github.com/Banno/asdf-hashicorp.git
  when: not tfresult.stat.exists
- name: install latest terraform
  shell: asdf install terraform $(asdf list-all terraform | grep -v beta | grep -v rc | grep -v alpha | tail -n 1)
- name: set latest terraform version
  shell: asdf global terraform $(asdf list-all terraform | grep -v beta | grep -v rc | grep -v alpha | tail -n 1)
