---
- shell: touch ~/.zshenv
- name: setup .zshenv
  blockinfile:
    dest: ~/.zshenv
    content: |
      autoload -Uz compinit vcs_info
      compinit
      zstyle ':vcs_info:*' formats '(%s)[%b]'
      zstyle ':vcs_info:*' actionformats '(%s)[%b|%a]'
      precmd () { vcs_info }
      setopt prompt_subst
      RPROMPT=$RPROMPT'${vcs_info_msg_0_}'

- shell: touch ~/.zshrc
- name: load .zshrc file
  lineinfile:
    dest: ~/.zshrc
    line: 'source ~/.bash_profile'
- name: setup .zshrc
  blockinfile:
    dest: ~/.zshrc
    content: |
      source ~/.bash_profile
      if [[ -s ~/.zprezto/init.zsh ]]; then source ~/.zprezto/init.zsh ; fi
      fpath=(/usr/local/share/zsh-completions $fpath)
      function peco-history-selection() {
        BUFFER=`history -n 1 | tail -r  | awk '!a[$0]++' | peco`
        CURSOR=$#BUFFER
        zle reset-prompt
      }
      zle -N peco-history-selection
      bindkey '^R' peco-history-selection

- name: git clone .zprezto
  git:
    repo: git@github.com:sorin-ionescu/prezto.git
    dest: ~/.zprezto
    force: yes
- name: symbolic link for .zprezto runcoms
  file:
    state: link
    src: ~/.zprezto/runcoms/{{ item }}
    path: ~/.{{ item }}
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
- name: change .zprezto editor
  replace:
    dest: ~/.zprofile
    regexp: ^'nano'$
    replace: 'vim'
