---
- name: setup .zshenv
  blockinfile:
    dest: ~/.zshenv
    content: |
      FPATH=/opt/homebrew/share/zsh-completions:$FPATH
      autoload -Uz compinit vcs_info
      compinit
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK for zshenv"

- name: setup .zshrc
  blockinfile:
    dest: ~/.zshrc
    content: |
      if [[ -s ~/.zprezto/init.zsh ]]; then source ~/.zprezto/init.zsh ; fi
      source ~/.bash_profile
      zstyle ':vcs_info:git:*' check-for-changes true
      zstyle ':vcs_info:git:*' stagedstr "%F{yellow}!"
      zstyle ':vcs_info:git:*' unstagedstr "%F{red}+"
      zstyle ':vcs_info:*' formats '(%s)%F{green}%c%u[%b]%f'
      zstyle ':vcs_info:*' actionformats '(%s)[%b|%a]'
      precmd () { vcs_info }
      setopt prompt_subst
      PROMPT='${vcs_info_msg_0_}'$'\n'$PROMPT
      function peco-history-selection() {
        BUFFER=`history -n 1 | tail -r  | awk '!a[$0]++' | peco`
        CURSOR=$#BUFFER
        zle reset-prompt
      }
      zle -N peco-history-selection
      bindkey '^R' peco-history-selection
      if [ ! -e ~/.zshrc.zwc ] || [ ~/.zshrc -nt ~/.zshrc.zwc ]; then zcompile ~/.zshrc ; fi
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK for zshrc"

- name: git clone .zprezto
  git:
    repo: git@github.com:sorin-ionescu/prezto.git
    dest: ~/.zprezto
    force: yes
- name: symbolic link for .zprezto runcoms
  file:
    state: link
    src: ~/.zprezto/runcoms/{{ item }}
    path: ~/.{{ item }}
    force: yes
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
- name: change .zprezto editor
  replace:
    dest: ~/.zprofile
    regexp: (.+?)'nano'$
    replace: \1'vim'
