---
- name: update brew
  homebrew:
    update_homebrew: yes
- name: install/upgrade brew packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
  with_items: "{{ brew_packages }}"
  when: brew_packages is defined and brew_packages | length > 0
- name: changing perm of homebrew share
  file:
    dest: /opt/homebrew/share
    mode: go-w
