---
- name: tap brew repositories
  homebrew_tap:
    tap: '{{ item }}'
    state: present
  with_items: '{{ brew_repositories }}'
  when: brew_repositories
- name: update brew
  homebrew:
    update_homebrew: yes
- name: install/upgrade brew packages
  homebrew:
    name: '{{ item.name | default(item) }}'
    state: "{{ item.state | default('latest') }}"
  with_items: '{{ brew_packages }}'
  when: brew_packages
- name: changing perm of homebrew share
  file:
    dest: /opt/homebrew/share
    mode: go-w
