---
- name: tap external brew cask repositories
  homebrew_tap:
    tap: '{{ item }}'
    state: present
  with_items: '{{ brew_cask_repositories }}'
  when: brew_cask_repositories
- name: install/upgrade brew cask packages
  homebrew_cask:
    name: '{{ item.name | default(item) }}'
    state: "{{ item.state | default('present') }}"
  with_items: '{{ brew_cask_packages }}'
  when: brew_cask_packages
