---
- name: install/upgrade brew cask packages
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    accept_external_apps: true
  with_items: "{{ brew_cask_packages }}"
  when: brew_cask_packages | length > 0
